name: Metrics and Snake Animation

on:
  schedule:
    - cron: '0 */24 * * *' # Runs every 24 hours
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          user: yml-blog
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          config_order: code, base.header, base.activity+community, base.repositories, notable, stargazers, people, habits, activity, followup, languages, isocalendar
          plugin_activity: yes
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_traffic: yes

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate GitHub contribution grid snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: Push GitHub contribution grid snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
