name: Metrics and Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          user: yml-blog
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_activity: yes
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_traffic: yes
          
      # 单独生成isocalendar年度贡献图
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          user: yml-blog
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # 生成贪吃蛇动画
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: yml-blog
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      # 推送到输出分支
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
